# Generated by Django 5.1.2 on 2025-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_created_at_product_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_date',
            new_name='date_sold',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='quantity',
            new_name='quantity_sold',
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('maize', 'Maize'), ('rice', 'Rice'), ('wheat', 'Wheat'), ('millet', 'Millet'), ('sorghum', 'Sorghum'), ('oats', 'Oats')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
